- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create 'config' in /home/{{ ansible_user_id }}/.ssh if it doesn't exist
      file:
        path: /home/{{ ansible_user_id }}/.ssh/config
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
        mode: 0751
        state: touch

    - name: Set up '~/.ssh/config' to allow ssh agent forwarding
      blockinfile:
        path: /home/{{ ansible_user_id }}/.ssh/config
        backup: yes

        # Here you configure which host to forward from the inventory file

        block: "Host {{groups['Production_Host'][0]}}\n\tForwardAgent yes"
        state: present
    

    - name: Create .ansible.cfg in /home/{{ ansible_user_id }} if it doesn't exist
      file:
        path: /home/{{ ansible_user_id }}/.ansible.cfg
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
        mode: 0751
        state: touch

    - name: Change .ansible.cfg to enable ssh agent forwarding
      blockinfile:
        path: /home/{{ ansible_user_id }}/.ansible.cfg
        backup: yes
        block: "[ssh_connection]\nssh_args = -C -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
        state: present

        