- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    packages:
      - git
      - apache2
  vars_files:
    - conf/websites.yml
  tasks:
    - name: install packages 
      apt: name={{ packages }} update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2
  
    - include: create_virtual_host.yml website="{{ item }}"
      loop: "{{ websites }}" 

    # - name: a2ensite everything 
    #   command: a2ensite {{ item }}
    #   args:
    #     creates: /etc/apache2/sites-enabled/{{ item.domain }}.conf
    #   notify:
    #     - restart apache2
    #   loop: "{{ websites }}"
    
    # - name: clone basic html template
    #   git: repo=https://github.com/do-community/ansible-apache-tutorial.git dest=/var/www/example.com update=no

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
