- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    packages:
      - git
      - apache2
      - git-lfs
  vars_files:
    - conf/websites.yml
    - conf/git_username_password.yml

  roles:
    - { role: capotej.packagecloud, repository: github/git-lfs, os: ubuntu, version: xenial }
  tasks:
    - name: install packages 
      apt: 
        name: "{{ packages }}"
        update_cache: yes
        state: latest
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2
  
    - include_tasks: create_virtual_host.yml
      vars: 
        domain: "{{ item.domain }}"
      loop: "{{ websites }}" 

    - name: a2ensite everything 
      command: a2ensite {{ item.domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ item.domain }}.conf
      notify:
        - restart apache2
      loop: "{{ websites }}"
  
    - name: Get updated files from git repository 
      git: 
        repo: "https://{{ github_username | urlencode }}:{{ github_password | urlencode }}@github.com/{{ github_username | urlencode }}/{{ item.repo }}"
        dest: /var/www/{{ item.domain }}
        update: no
      loop: "{{ websites }}"

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
